version: "3.8"
services:
  devgame_db:
    container_name: DevGame_Database
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: always
    env_file: .env 
    ports:
      - 127.0.0.1:3306:3306 # only bind port locally for now
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql

  devgame_backend:
    container_name: devGame_backend
    build:
      context: ./backend
    env_file: .env
    restart: always
    volumes: 
      - ./backend/devgame_django:/devgame_django
    depends_on:
      - devgame_db
    working_dir: "/devgame_django"
    expose:
      - 8081
    ports:
      - 127.0.0.1:8081:8081 # only bind port locally for now

    # command: ["python", "manage.py", "makemigrations"] 
    # command: ["python", "manage.py", "migrate"]
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8081'
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8081"]

  devgame_frontend:
      container_name: devgame_frontend
      build:
        context: ./frontend
      depends_on:
        - devgame_backend
      # restart: always
      volumes: 
      - ./frontend/devgame_react:/devgame_react
      ports:
        - 127.0.0.1:8080:8080 # only bind port locally for now
      working_dir: "/devgame_react"
      environment:
        - PORT=8080
      command: npm start

volumes:
  my-db: